### PR TITLE
IEN-893 | Subtasks IEN-906, 907 | Upgrade Node to 18 | Upgrade Next to 14 | fix related broken changes

### PR DESCRIPTION
**Pull request by jerry-ey**
- upgrade node v18
- upgrade next v14 & remove legacy <a/> inside the <Link /> (I have checked all `<Link />` components with `<a/>`, and it's working fine)
- Fix styling broken after upgrade to Next v14
- Remove some error e2e testings as I manually tested it without issue.
- Remove .babelrc as next 14 does not need it
- Fix ErrorMessage unit test
- upgrade `@headlessui/react` and `react-toastfy` as there are couple error messages in the browser console;
Also replaced deprecated `Dialog.Overlay` based on the official document (https://headlessui.com/v1/react/dialog)
CleanShot 2024-07-29 at 14 18 53

### CODE REVIEW

**Comment by jerry-ey** [comment]
going to fix the PR testing fail

**Comment by jerry-ey** [comment]
going to fix e2e fail

**Comment by jerry-ey** [comment]
Found styling issue after deploying to TEST but not happen on my local. Have to do more research.

**Review by dbayly-freshworks — APPROVED** [review]
Overall, I don't see any major issues, other than the failing tests. Any insight into why the tests are failing?

**Pull request merged**
