### PR TITLE
Added log for request-response with the help of middleware.

### PR DESCRIPTION
**Pull request by bhumin-fw**

### CODE REVIEW

**Comment by bhumin-fw** [comment]
@sunghwan-park-fw 
Added a middleware that log request and relative response. It will log the below data from the request & response object combined.
`${method} ${originalUrl} ${statusCode} - ${userAgent} ${ip}`
cc: @coryatwater-FW 

Please provide your thought on this.
If this looks good, I will remove the informative message/log from all the controller functions.
And keep only business or logical messages in service, util & common files.

**Comment by sunghwan-park-fw** [comment]
Looks good. I just wonder if we need to log requests before processing apart from logging response.

**Comment by bhumin-fw** [comment]
> Looks good. I just wonder if we need to log requests before processing apart from logging response.

@sunghwan-park-fw 
I don’t think so, as i have added log under close loop.
We will only miss request log if sever suddenly stopped working in between request and response.

Do you think that’s a high severity information we might miss?

**Comment by sunghwan-park-fw** [comment]
> > Looks good. I just wonder if we need to log requests before processing apart from logging response.
> 
> @sunghwan-park-fw I don’t think so, as i have added log under close loop. We will only miss request log if sever suddenly stopped working in between request and response.
> 
> Do you think that’s a high severity information we might miss?

No. It seems enough as it is.

**Review by sunghwan-park-fw — APPROVED** [review]

**Pull request merged**
